<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>MaBoutique.Auth.Api</AssemblyName>
    <RootNamespace>MaBoutique.Auth.Api</RootNamespace>
    <UserSecretsId>MaBoutique-Auth-Api-dev</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MaBoutique.Auth.Application\MaBoutique.Auth.Application.csproj" />
    <ProjectReference Include="..\MaBoutique.Auth.Infrastructure\MaBoutique.Auth.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\..\shared\MaBoutique.BuildingBlocks\MaBoutique.BuildingBlocks.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="9.0.4" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.1" />
  </ItemGroup>
</Project>